kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  AVP_AUTH_TYPE: "k8s"
  AVP_K8S_ROLE: "argocd"
  AVP_TYPE: "vault"
  VAULT_ADDR: "http://vault.vault:8200"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
      init:
        command:
          - bash
          - "-c"
          - |
            helm repo add bitnami https://charts.bitnami.com/bitnami
            helm repo add cert-manager https://charts.jetstack.io
            helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/ 
            helm repo add jameswynn https://jameswynn.github.io/helm-charts
            helm repo add common https://bjw-s.github.io/helm-charts
            helm repo add openldap https://jp-gouin.github.io/helm-openldap/
            helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
            helm repo add grafana https://grafana.github.io/helm-charts
            helm repo add authentik https://charts.goauthentik.io
            helm dependency build
      generate:
        command:
          - bash
          - "-c"
          - |
            HELM_OUTPUT=$(helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE -f <(echo "$ARGOCD_ENV_HELM_VALUES") .)
            SKIP_VAULT=$(echo "$ARGOCD_ENV_HELM_VALUES" | grep -i "skipVaultPlugin" | grep -i "true" || true)
            if [[ -z "$SKIP_VAULT" ]]; then
              echo "$HELM_OUTPUT" | argocd-vault-plugin generate -s argocd:argocd-vault-plugin-credentials -
            else
              echo "$HELM_OUTPUT"
            fi
      lockRepo: false

---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: argocd
  namespace: argocd
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "argocd.vpn.rjst.de"
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        credentialName: argocd-cert
        mode: SIMPLE
      hosts:
        - "argocd.vpn.rjst.de"

---

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: argocd
  namespace: argocd
spec:
  hosts:
    - "argocd.vpn.rjst.de"
  gateways:
    - argocd
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: argocd-server
            port:
              number: 80

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: istio-system
spec:
  secretName: argocd-cert
  issuerRef:
    name: self-issuer
    kind: ClusterIssuer
  commonName: "argocd.vpn.rjst.de"
  dnsNames:
    - "argocd.vpn.rjst.de"
