apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ""

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: cert-manager
  name: letsencrypt
spec:
  acme:
    email: business.rst@outlook.de
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        cloudflare:
          email: business.rst@outlook.de
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: ca-self-secret

---

apiVersion: v1
kind: Secret
metadata:
  name: ca-self-secret
  namespace: cert-manager
type: Opaque
data:
  tls.crt: ""
  tls.key: ""
