apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  destination:
    namespace: uptime-kuma
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://dirsigler.github.io/uptime-kuma-helm
    chart: uptime-kuma
    targetRevision: 2.22.0
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            resources:
              requests:
                cpu: 0m
                memory: 0Mi
              limits:
                cpu: 250m
                memory: 512Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "status.rjst.de"
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        credentialName: uptime-kuma-cert
        mode: SIMPLE
      hosts:
        - "status.rjst.de"

---

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  hosts:
    - "status.rjst.de"
  gateways:
    - uptime-kuma
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: uptime-kuma
            port:
              number: 3001

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-kuma-cert
  namespace: istio-system
spec:
  secretName: uptime-kuma-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "status.rjst.de"
  dnsNames:
    - "status.rjst.de"
