apiVersion: v1
kind: Secret
metadata:
  namespace: vault
  name: vault-unsealer-config
  labels:
    vault-unsealer.bakito.net/stateful-set: vault
  annotations:
    avp.kubernetes.io/path: "argocd/data/ca"
type: Opaque
stringData:
  unsealKey1: <unsealKey1>
  unsealKey2: <unsealKey2>
  unsealKey3: <unsealKey3>
  unsealKey4: <unsealKey4>
  unsealKey5: <unsealKey5>
