apiVersion: v1
kind: Namespace
metadata:
  name: wireguard

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-easy
  namespace: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wg-easy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wg-easy
    spec:
      containers:
        - name: wg-easy
          env:
            - name: WG_HOST
              value: vpn.rjst.de
            - name: WG_INSECURE
              value: "false"
            - name: WG_DISABLE_IPV6
              value: "true"
          image: ghcr.io/wg-easy/wg-easy:15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 51820
              name: wg
              protocol: UDP
            - containerPort: 51821
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          volumeMounts:
            - mountPath: /etc/wireguard
              name: config
            - mountPath: /lib/modules
              name: modules
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: wg-easy-storage
        - name: modules
          hostPath:
            path: /lib/modules
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy-storage
  namespace: wireguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: wg-easy-wg
  namespace: wireguard
spec:
  ports:
    - name: wg
      port: 51820
      protocol: UDP
      targetPort: wg
  selector:
    app.kubernetes.io/name: wg-easy
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: wg-easy-http
  namespace: wireguard
spec:
  ports:
    - name: http
      port: 51821
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: wg-easy
  type: ClusterIP

---

apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: wireguard
  namespace: wireguard
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "wireguard.vpn.rjst.de"
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        credentialName: wireguard-cert
        mode: SIMPLE
      hosts:
        - "wireguard.vpn.rjst.de"

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wireguard-cert
  namespace: istio-system
spec:
  secretName: wireguard-cert
  issuerRef:
    name: self-issuer
    kind: ClusterIssuer
  commonName: "wireguard.vpn.rjst.de"
  dnsNames:
    - "wireguard.vpn.rjst.de"

---

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: wireguard
  namespace: wireguard
spec:
  hosts:
    - "wireguard.vpn.rjst.de"
  gateways:
    - wireguard
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: wg-easy-http
            port:
              number: 51821
