apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    istio-injection: enabled

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring
  namespace: dev

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-spring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: spring
    namespace: dev
