apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: vault
  namespace: vault
spec:
  hosts:
    - "vault.vpn.rjst.de"
  gateways:
    - vault
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: vault
            port:
              number: 8200



---

apiVersion: v1
kind: Secret
metadata:
  namespace: vault
  name: vault-unsealer-config
  labels:
    vault-unsealer.bakito.net/stateful-set: vault
  annotations:
    avp.kubernetes.io/path: "argocd/data/vault"
type: Opaque
stringData:
  unsealKey1: <unsealKey1>
  unsealKey2: <unsealKey2>
  unsealKey3: <unsealKey3>
  unsealKey4: <unsealKey4>
  unsealKey5: <unsealKey5>
