apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd

spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://helm.releases.hashicorp.com
    chart: vault
    helm:
      valueFiles: 
      - $values/vault/values.yaml
    targetRevision: 0.31.0
  - repoURL: https://github.com/ToXiCCuss/gitops-kubernetes.git
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
